
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author choha
 */
public class admissionframe extends javax.swing.JFrame {

    /**
     * Creates new form admissionframe
     */
    public admissionframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcombo1 = new javax.swing.JComboBox<>();
        jlabel1 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlabel2 = new javax.swing.JLabel();
        jlabel10 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel11 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        jlabel12 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jlabel13 = new javax.swing.JLabel();
        jlabel17 = new javax.swing.JLabel();
        jlabel18 = new javax.swing.JLabel();
        jlabel19 = new javax.swing.JLabel();
        jlabel20 = new javax.swing.JLabel();
        jlabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jlabel14 = new javax.swing.JLabel();
        jlabel15 = new javax.swing.JLabel();
        jlabel16 = new javax.swing.JLabel();
        jlabel22 = new javax.swing.JLabel();
        jlabel23 = new javax.swing.JLabel();
        jlabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\cancle (2).jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 6, 77, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\fees (1).jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 19, 37, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 3, 18)); // NOI18N
        jLabel3.setText("SELECT YOUR CATEGORY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 94, 228, -1));

        jcombo1.setFont(new java.awt.Font("Segoe UI Variable", 3, 18)); // NOI18N
        jcombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "SC OR ST", " " }));
        jcombo1.setSelectedItem(null);
        jcombo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcombo1MouseClicked(evt);
            }
        });
        jcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jlabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 200, 28));

        jlabel9.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 80, 25));

        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 3, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jlabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 220, 28));

        jlabel10.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 80, 25));

        jlabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, 28));

        jlabel11.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 80, 25));

        jlabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 190, 28));

        jlabel12.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 80, 25));

        jlabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 190, 28));

        jlabel13.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 80, 25));

        jlabel17.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        getContentPane().add(jlabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 80, 25));

        jlabel18.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        getContentPane().add(jlabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 80, 25));

        jlabel19.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        getContentPane().add(jlabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 350, 21));

        jlabel20.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        getContentPane().add(jlabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 80, 25));

        jlabel21.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        getContentPane().add(jlabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 80, 25));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel19.setText("ADMISSION FEES");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 200, 40));

        jlabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 28));

        jlabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 190, 28));

        jlabel8.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 230, 28));

        jlabel14.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 80, 25));

        jlabel15.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 80, 25));

        jlabel16.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        getContentPane().add(jlabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 80, 25));

        jlabel22.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        getContentPane().add(jlabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 390, 35));

        jlabel23.setFont(new java.awt.Font("Old English Text MT", 3, 18)); // NOI18N
        jlabel23.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jlabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 80, 25));

        jlabel24.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        getContentPane().add(jlabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 350, 25));
        jlabel24.getAccessibleContext().setAccessibleName("jlabel24");

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\pexels-codioful-(formerly-gradienta)-7130470 (1) (1).jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        setBounds(500, 150, 780, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
//        studentfeesframe obj=new studentfeesframe();
//        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

               String cat=jcombo1.getSelectedItem().toString();
              
               if(cat.equals("GENERAL"))
               {
                    jlabel24.setText("");
                   jlabel1.setText("HOSTEL FORM");
                   jlabel2.setText("HOSTEL SECURITY(ONCE)");
                   jlabel3.setText("HOSTEL FEES");
                   jlabel4.setText("MESS SECURITY(ONCE)");
                   jlabel5.setText("WELFARE CHARGES");
                   jlabel6.setText("WATER CHARGES");
                   jlabel7.setText("ELECTRICITY CHARGES");
                   jlabel8.setText("MAINTENANCE CHARGES");
                   jlabel9.setText("100");
                   jlabel10.setText("2000");
                   jlabel11.setText("500");
                   jlabel12.setText("910");
                   jlabel13.setText("410");
                   jlabel14.setText("500");
                   jlabel15.setText("2800");
                   jlabel16.setText("3000");
                   jlabel17.setText("TOTAL");
                   jlabel18.setText("10220");
                   jlabel19.setText("IF PARKING NEEDED ADDITIONAL 400");
                   jlabel20.setText("TOTAL");
                   jlabel21.setText("10620");
                   jlabel23.setText("NOTE");
                   jlabel22.setText("SECURITY AND MESS CHARGES ARE REFULDABLE");
               }
               else if(cat.equals("SC OR ST"))
               {
                    jlabel24.setText("");
                    jlabel1.setText("HOSTEL FORM");
                   jlabel2.setText("HOSTEL SECURITY(ONCE)");
                   jlabel3.setText("HOSTEL FEES");
                   jlabel4.setText("MESS SECURITY(ONCE)");
                   jlabel5.setText("WELFARE CHARGES");
                   jlabel6.setText("WATER CHARGES");
                   jlabel7.setText("ELECTRICITY CHARGES");
                   jlabel8.setText("MAINTENANCE CHARGES");
                   jlabel9.setText("100");
                   jlabel10.setText("2000");
                   jlabel11.setText("200");
                   jlabel12.setText("910");
                   jlabel13.setText("210");
                   jlabel14.setText("200");
                   jlabel15.setText("2000");
                   jlabel16.setText("1000");
                   jlabel17.setText("TOTAL");
                   jlabel18.setText("6620");
                   jlabel19.setText("IF PARKING NEEDED ADDITIONAL 200");
                   jlabel20.setText("TOTAL");
                   jlabel21.setText("6820");
                   jlabel23.setText("NOTE");
                   jlabel22.setText("SECURITY AND MESS CHARGES ARE REFULDABLE");
               }
               else
               {
                   jlabel24.setText("PLS CHOOSE CORRECT OPTION");
                   jlabel1.setText("");
                   jlabel2.setText("");
                   jlabel3.setText("");
                   jlabel4.setText("");
                   jlabel5.setText("");
                   jlabel6.setText("");
                   jlabel7.setText("");
                   jlabel8.setText("");
                   jlabel9.setText("");
                   jlabel10.setText("");
                   jlabel11.setText("");
                   jlabel12.setText("");
                   jlabel13.setText("");
                   jlabel14.setText("");
                   jlabel15.setText("");
                   jlabel16.setText("");
                   jlabel17.setText("");
                   jlabel18.setText("");
                   jlabel19.setText("");
                   jlabel20.setText("");
                   jlabel21.setText("");
                   jlabel23.setText("");
                   jlabel22.setText(""); 
               }
     


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        studentfeesframe ob1=new studentfeesframe();
        ob1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcombo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcombo1MouseClicked
        // TODO add your handling code here:
        jlabel1.setText("");
                   jlabel2.setText("");
                   jlabel3.setText("");
                   jlabel4.setText("");
                   jlabel5.setText("");
                   jlabel6.setText("");
                   jlabel7.setText("");
                   jlabel8.setText("");
                   jlabel9.setText("");
                   jlabel10.setText("");
                   jlabel11.setText("");
                   jlabel12.setText("");
                   jlabel13.setText("");
                   jlabel14.setText("");
                   jlabel15.setText("");
                   jlabel16.setText("");
                   jlabel17.setText("");
                   jlabel18.setText("");
                   jlabel19.setText("");
                   jlabel20.setText("");
                   jlabel21.setText("");
                   jlabel23.setText("");
                   jlabel22.setText(""); 
      
    }//GEN-LAST:event_jcombo1MouseClicked

    private void jcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admissionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admissionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admissionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admissionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admissionframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcombo1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JLabel jlabel13;
    private javax.swing.JLabel jlabel14;
    private javax.swing.JLabel jlabel15;
    private javax.swing.JLabel jlabel16;
    private javax.swing.JLabel jlabel17;
    private javax.swing.JLabel jlabel18;
    private javax.swing.JLabel jlabel19;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel20;
    private javax.swing.JLabel jlabel21;
    private javax.swing.JLabel jlabel22;
    private javax.swing.JLabel jlabel23;
    private javax.swing.JLabel jlabel24;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    // End of variables declaration//GEN-END:variables
}
