import java.awt.Color;
//import java.lang.Thread.sleep;
import java.sql.Statement;
import javax.swing.JButton;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author choha
 */
public class block1frame extends javax.swing.JFrame {

    public void tabel() {
        DefaultTableModel dt=(DefaultTableModel)jtabel.getModel();
        dt.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st = cot.createStatement();
            ResultSet rs = st.executeQuery("Select * from block1");
            while (rs.next()) {
                int number = rs.getInt("number");
                String activate = rs.getString("activate");
                String roomstatus = rs.getString("roomstatus");
                Object[] tbdata = {number, activate, roomstatus};
             
                dt.addRow(tbdata);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(block1frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public block1frame() {
        initComponents();
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtext1 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jlabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbutton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabel.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMBER", "ACTIVATE", "ROOM STATUS"
            }
        ));
        jtabel.setToolTipText("");
        jtabel.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jtabel);
        jtabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 377, 460, 235));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("ALL ROOMS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 150, 40));

        jLabel2.setFont(new java.awt.Font("Wide Latin", 3, 18)); // NOI18N
        jLabel2.setText("BLOCK  1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 18, 206, 31));

        jLabel3.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel3.setText("UPDATE ROOM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 82, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel4.setText("ROOM NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        jtext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtext1MouseClicked(evt);
            }
        });
        jtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext1ActionPerformed(evt);
            }
        });
        jtext1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext1KeyPressed(evt);
            }
        });
        getContentPane().add(jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 30));

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\search (1).jpeg")); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 130, -1));

        jCheckBox1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jCheckBox1.setText("ACTIVATE OR DEACTIVATE");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 240, 30));

        jCheckBox2.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jCheckBox2.setText("BOOKED OR NOT");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 200, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\update (1).jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 70, 30));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\update (1).jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 70, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, 784, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\cancle (2).jpeg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        jlabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        getContentPane().add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 310, 30));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        jbutton6.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jbutton6.setText("SUBMIT");
        jbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 110, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\pexels-codioful-(formerly-gradienta)-7130470 (1) (1).jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        setBounds(500, 150, 790, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton6ActionPerformed
        jbutton6.setBackground(Color.red);
        jbutton6.setForeground(Color.PINK);
 DefaultTableModel dt=(DefaultTableModel)jtabel.getModel();
        dt.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            //Statement st=(Statement) cot.createStatement();
            Statement st = cot.createStatement();
            ResultSet rs = st.executeQuery("Select * from block1");
            while (rs.next()) {
                int number = rs.getInt("number");
                String activate = rs.getString("activate");
                String roomstatus = rs.getString("roomstatus");
                Object[] tbdata = {number, activate, roomstatus};
               
                dt.addRow(tbdata);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(block1frame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbutton6ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        jbutton6.setForeground(new JButton().getForeground());
        jbutton6.setBackground(new JButton().getBackground());

    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       jCheckBox1.setEnabled(true);
       jCheckBox2.setEnabled(true);
        String roomnumber = jtext1.getText();
        int i = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st1 = cot1.createStatement();
            ResultSet rs1 = st1.executeQuery("Select * from block1 Where number='" + roomnumber + "'");
            while (rs1.next()) {
                i = 1;
                if (rs1.getString(3).equals("BOOKED")) {
                    jlabel1.setText("ROOM ALREADY BOOKED");
                    if(rs1.getString(2).equals("YES")&& rs1.getString(3).equals("BOOKED"))
                    {
                        jCheckBox2.setSelected(true);
                        jCheckBox1.setSelected(true);
                    }
                   jCheckBox2.setSelected(true);
//            sleep(4000);
//           jlabel1.setText(" ");
                    //jtext1.setText(" ");
                } 
                else {
                    jlabel1.setText("");
                    jtext1.setEditable(true);
                    
                    if (rs1.getString(2).equals("YES")) {
                        jCheckBox1.setSelected(true);
                    } 
                    
                    else
                    {
                        jCheckBox1.setSelected(false);
                        jCheckBox2.setSelected(false);
                    }
                }

            }
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "ROOM NUMBER DOES NOT EXIST");
            }
        } catch ( ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String roomnumber = jtext1.getText();
        String activate;
        if (jCheckBox1.isSelected()) {
            activate = "YES";
        } else {
            activate = "NO";
        }
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st1 = cot1.createStatement();
            st1.executeUpdate("update block1 set activate='" + activate + "' Where number='" + roomnumber + "'");
            JOptionPane.showMessageDialog(null, "ROOM IS UPDATED");
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jtext1.setText(" ");
            jlabel1.setText("");
            tabel();

        } catch ( ClassNotFoundException | SQLException e) {

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String roomnumber = jtext1.getText();
        String roomstatus;
        if (jCheckBox2.isSelected()) {
            roomstatus = "BOOKED";
        } else {
            roomstatus = "NOTBOOKED";
        }
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st1 = cot1.createStatement();
            st1.executeUpdate("update block1 set roomstatus='" + roomstatus + "' Where number='" + roomnumber + "'");
            JOptionPane.showMessageDialog(null, "ROOM STATUS IS UPDATED");
             jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jlabel1.setText("");
            jtext1.setText(" ");
            tabel();

        } catch ( ClassNotFoundException | SQLException e) {

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtext1MouseClicked
        // TODO add your handling code here:
        jtext1.setText("");
        jlabel1.setText("");
         jCheckBox1.setEnabled(false);
       jCheckBox2.setEnabled(false);
        jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
    }//GEN-LAST:event_jtext1MouseClicked

    private void jtext1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext1KeyPressed
    
        char d=evt.getKeyChar();
 if(Character.isDigit(d))
     jtext1.setVisible(true);
 else
 {
     JOptionPane.showMessageDialog(null, "pls enter digits only");
     jtext1.setText("");
    
 }
    }//GEN-LAST:event_jtext1KeyPressed

    private void jtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(block1frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new block1frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbutton6;
    private javax.swing.JLabel jlabel1;
    public javax.swing.JTable jtabel;
    private java.awt.TextField jtext1;
    // End of variables declaration//GEN-END:variables
}
