
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

public class newstudentframe extends javax.swing.JFrame {

    public void roomnumber() {
        int i = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            String block = jcombo1.getSelectedItem().toString();
            String query = "SELECT number FROM " + block + " WHERE  roomstatus= 'NOTBOOKED' AND activate = 'YES'";
            PreparedStatement stmt = cot.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                i = 1;
                jComboBox1.addItem(rs.getString(1));

            }
            if (i == 0) {
                jbutton1.setVisible(false);
                JOptionPane.showMessageDialog(null, "ROOMS ARE ALREADY BOOKED");

            }
        } catch (Exception e) {

        }

    }

    public newstudentframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtext1 = new java.awt.TextField();
        jtext2 = new java.awt.TextField();
        jtext3 = new java.awt.TextField();
        jtext4 = new java.awt.TextField();
        jtext5 = new java.awt.TextField();
        jtext6 = new java.awt.TextField();
        jtext7 = new java.awt.TextField();
        jtext8 = new java.awt.TextField();
        jtext9 = new java.awt.TextField();
        jcombo1 = new javax.swing.JComboBox<>();
        jbutton1 = new javax.swing.JButton();
        jbutton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jdate2 = new com.toedter.calendar.JDateChooser();
        jdate1 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\cancle (2).jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 80, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel2.setText("ENTER STUDENT DETAILS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 250, 30));

        jtext1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext1ActionPerformed(evt);
            }
        });
        jtext1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext1KeyPressed(evt);
            }
        });
        getContentPane().add(jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 70, -1));

        jtext2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext2KeyPressed(evt);
            }
        });
        getContentPane().add(jtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 290, -1));

        jtext3.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext3.setText(" ");
        jtext3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext3KeyPressed(evt);
            }
        });
        getContentPane().add(jtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 290, -1));

        jtext4.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext4.setText(" ");
        jtext4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext4KeyPressed(evt);
            }
        });
        getContentPane().add(jtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 290, -1));

        jtext5.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext5.setText(" ");
        jtext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext5ActionPerformed(evt);
            }
        });
        jtext5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext5KeyPressed(evt);
            }
        });
        getContentPane().add(jtext5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 290, -1));

        jtext6.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext6.setText(" ");
        jtext6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtext6MouseClicked(evt);
            }
        });
        jtext6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext6KeyPressed(evt);
            }
        });
        getContentPane().add(jtext6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 290, -1));

        jtext7.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext7.setText(" ");
        jtext7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtext7MouseClicked(evt);
            }
        });
        jtext7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext7KeyPressed(evt);
            }
        });
        getContentPane().add(jtext7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 290, -1));

        jtext8.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext8.setText(" ");
        getContentPane().add(jtext8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 290, -1));

        jtext9.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext9.setText(" ");
        jtext9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext9ActionPerformed(evt);
            }
        });
        getContentPane().add(jtext9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 290, -1));

        jcombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "block1", "block2", "block3" }));
        jcombo1.setSelectedItem(null);
        jcombo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcombo1MouseClicked(evt);
            }
        });
        jcombo1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jcombo1ComponentShown(evt);
            }
        });
        jcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 100, -1));

        jbutton1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jbutton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\update (1).jpg")); // NOI18N
        jbutton1.setText("SAVE");
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        jbutton2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jbutton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\sp (1).jpeg")); // NOI18N
        jbutton2.setText("CLEAR");
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setText("HOSTEL ROLL NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel5.setText("FATHER NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel6.setText("MOTHER NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel7.setText("EMAIL ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel8.setText("AADHAAR NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel9.setText("ROOM NUMBER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel10.setText("MOBILE NUMBER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 190, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel11.setText("DEPARTMENT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel12.setText("PERMANENT ADDRESS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 200, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\st (1).jpeg")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 60));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel14.setText("SELECT BLOCK NUMBER");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel15.setText("DOB");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 190, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 290, -1));

        jdate2.setDateFormatString("yyyy-MM-dd");
        jdate2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jdate2.setPreferredSize(new java.awt.Dimension(117, 22));
        getContentPane().add(jdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 290, 30));

        jdate1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 70, 130, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel18.setText("DATE OF JOINING");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 140, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\pexels-codioful-(formerly-gradienta)-7130470 (1) (1).jpg")); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        setBounds(500, 150, 750, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void jcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo1ActionPerformed
        roomnumber();

    }//GEN-LAST:event_jcombo1ActionPerformed

    private void jtext9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext9ActionPerformed

    private void jtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
        jtext1.setText("");
        jtext2.setText("");
        jtext3.setText("");
        jtext4.setText("");
        jtext5.setText("");
        jtext6.setText("");
        jtext7.setText("");
        jtext8.setText("");
        jtext9.setText("");
        jComboBox1.removeAllItems();
        jcombo1.setSelectedItem(null);


    }//GEN-LAST:event_jbutton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        // roomnumber();
    }//GEN-LAST:event_formComponentShown

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jcombo1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jcombo1ComponentShown
        // TODO add your handling code here:
        //roomnumber();
    }//GEN-LAST:event_jcombo1ComponentShown

    private void jcombo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcombo1MouseClicked
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
    }//GEN-LAST:event_jcombo1MouseClicked

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed

        String hrno = jtext1.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            String sp = "select hrno from student where hrno=?";
            PreparedStatement st1 = cot.prepareStatement(sp);
            st1.setString(1, jtext1.getText());
            ResultSet cp = st1.executeQuery();
            if (cp.next()) {
                JOptionPane.showMessageDialog(null, "HOSTEL ROLL NUMBER ALREADY EXIST");
            } else {
                JOptionPane.showMessageDialog(null, "PLS ENTER OTHERS DETAILS");
                Date joiningdate = jdate1.getDate();
                Date joi = new java.sql.Date(joiningdate.getTime());
                String name = jtext2.getText();
                String fathername = jtext3.getText();
                String mothername = jtext4.getText();
                Date dob = (jdate2.getDate());
                Date dob1 = new java.sql.Date(dob.getTime());
                String email = jtext5.getText();
                String mobilenumber = jtext6.getText();
                String department = jtext7.getText();
                String address = jtext8.getText();
                String adhar = jtext9.getText();
                String block = (String) jcombo1.getSelectedItem();
                String room = (String) jComboBox1.getSelectedItem();
                String status = "LIVING";
                PreparedStatement pt = cot.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                //JOptionPane.showMessageDialog(null,"SUCCESSFULY ");
                pt.setString(1, hrno);
                pt.setDate(2, (java.sql.Date) joi);
                pt.setString(3, name);
                pt.setString(4, fathername);
                pt.setString(5, mothername);
                pt.setDate(6, (java.sql.Date) dob1);
                pt.setString(7, email);
                pt.setString(8, mobilenumber);
                pt.setString(9, department);
                pt.setString(10, address);
                pt.setString(11, adhar);
                pt.setString(12, block);
                pt.setString(13, room);
                pt.setString(14, status);
                JOptionPane.showMessageDialog(null, "SUCCESSFULY ");
                pt.setDate(15, null);
                pt.executeUpdate();
                String updateQuery = "UPDATE " + block + " SET roomstatus = 'BOOKED' WHERE number = ?";
                PreparedStatement stmt1 = cot.prepareStatement(updateQuery);
                stmt1.setString(1, room);
                stmt1.executeUpdate();
                JOptionPane.showMessageDialog(null, "SUCCESSFULY UPDATED");
                jtext1.setText("");
                jtext2.setText("");
                jtext3.setText("");
                jtext4.setText("");
                jtext5.setText("");
                jtext6.setText("");
                jtext7.setText("");
                jtext8.setText("");
                jtext9.setText("");
                jComboBox1.removeAllItems();
                jcombo1.setSelectedItem(null);

            }
        } catch (ClassNotFoundException | SQLException e) {

        }

    }//GEN-LAST:event_jbutton1ActionPerformed

    private void jtext1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext1KeyPressed
        char d = evt.getKeyChar();
        if (Character.isDigit(d))
            jtext1.setVisible(true);
        else {
            JOptionPane.showMessageDialog(null, "pls enter digits only");
            jtext1.setText("");

        }
    }//GEN-LAST:event_jtext1KeyPressed

    private void jtext2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext2KeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
            jtext2.setVisible(true);
        else {
            JOptionPane.showMessageDialog(null, "pls enter letters only");
            jtext2.setText("");

        }
    }//GEN-LAST:event_jtext2KeyPressed

    private void jtext3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext3KeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
            jtext3.setVisible(true);
        else {
            JOptionPane.showMessageDialog(null, "pls enter letters only");
            jtext3.setText("");

        }
    }//GEN-LAST:event_jtext3KeyPressed

    private void jtext4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext4KeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
            jtext4.setVisible(true);
        else {
            JOptionPane.showMessageDialog(null, "pls enter letters only");
            jtext4.setText("");

        }
    }//GEN-LAST:event_jtext4KeyPressed

    private void jtext7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext7KeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
            jtext7.setVisible(true);
        else {
            JOptionPane.showMessageDialog(null, "pls enter letters only");
            jtext7.setText("");

        }
    }//GEN-LAST:event_jtext7KeyPressed

    private void jtext5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext5KeyPressed

    }//GEN-LAST:event_jtext5KeyPressed

    private void jtext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext5ActionPerformed
        // TODO add your handling code here:
        if (jtext5 == null || jtext5.getText().length() < 10 || !(jtext5.getText().trim().contains("@") && jtext5.getText().trim().contains(".")))
            JOptionPane.showMessageDialog(null, "invalid email");
    }//GEN-LAST:event_jtext5ActionPerformed

    private void jtext6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtext6MouseClicked
        // TODO add your handling code here:
        if (jtext5 == null || jtext5.getText().length() < 10 || !(jtext5.getText().trim().contains("@") && jtext5.getText().trim().contains(".")))
            JOptionPane.showMessageDialog(null, "invalid email");
    }//GEN-LAST:event_jtext6MouseClicked

    private void jtext7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtext7MouseClicked
        if (jtext7 == null || jtext7.getText().length() < 11 || jtext7.getText().length() > 12 || (jtext7.getText().trim().contains(" ") && jtext7.getText().trim().contains(".")))
            JOptionPane.showMessageDialog(null, "enter correct number of 10 digits");
    }//GEN-LAST:event_jtext7MouseClicked

    private void jtext6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext6KeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isDigit(d)) {
            jtext6.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "pls enter digits only");
            jtext6.setText("");

        }

    }//GEN-LAST:event_jtext6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstudentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstudentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstudentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstudentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstudentframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton jbutton2;
    public javax.swing.JComboBox<String> jcombo1;
    private com.toedter.calendar.JDateChooser jdate1;
    public com.toedter.calendar.JDateChooser jdate2;
    private java.awt.TextField jtext1;
    public java.awt.TextField jtext2;
    private java.awt.TextField jtext3;
    private java.awt.TextField jtext4;
    private java.awt.TextField jtext5;
    private java.awt.TextField jtext6;
    private java.awt.TextField jtext7;
    private java.awt.TextField jtext8;
    private java.awt.TextField jtext9;
    // End of variables declaration//GEN-END:variables
}
