import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author choha
 */
public class searchframe extends javax.swing.JFrame {

    /**
     * Creates new form searchframe
     */
    public searchframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtext1 = new java.awt.TextField();
        jtext2 = new java.awt.TextField();
        jtext3 = new java.awt.TextField();
        jtext4 = new java.awt.TextField();
        jtext5 = new java.awt.TextField();
        jtext6 = new java.awt.TextField();
        jtext7 = new java.awt.TextField();
        jtext8 = new java.awt.TextField();
        jtext9 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jtext10 = new java.awt.TextField();
        jtext11 = new java.awt.TextField();
        jtext12 = new java.awt.TextField();
        jLabel13 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\cancle (2).jpeg")); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 80, -1));

        jtext1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext1ActionPerformed(evt);
            }
        });
        jtext1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext1KeyPressed(evt);
            }
        });
        getContentPane().add(jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, -1));

        jtext2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        getContentPane().add(jtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 290, -1));

        jtext3.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext3.setText(" ");
        getContentPane().add(jtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 290, -1));

        jtext4.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext4.setText(" ");
        getContentPane().add(jtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 290, -1));

        jtext5.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext5.setText(" ");
        getContentPane().add(jtext5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 290, -1));

        jtext6.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext6.setText(" ");
        getContentPane().add(jtext6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 290, -1));

        jtext7.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext7.setText(" ");
        getContentPane().add(jtext7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 290, -1));

        jtext8.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext8.setText(" ");
        getContentPane().add(jtext8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 290, -1));

        jtext9.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jtext9.setText(" ");
        jtext9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext9ActionPerformed(evt);
            }
        });
        getContentPane().add(jtext9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setText("HOSTEL ROLL NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel5.setText("FATHER NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel6.setText("MOTHER NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel7.setText("EMAIL ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel8.setText("AADHAAR NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel9.setText("ROOM NUMBER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel10.setText("MOBILE NUMBER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 190, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel11.setText("DEPARTMENT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 150, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel12.setText("PERMANENT ADDRESS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 200, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel14.setText("BLOCK NUMBER");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel15.setText("DOB");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 190, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel16.setText("ROOM STATUS");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\search (1).jpeg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 40, 30));

        jtext10.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        getContentPane().add(jtext10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 100, -1));

        jtext11.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        getContentPane().add(jtext11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 290, -1));

        jtext12.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        getContentPane().add(jtext12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 290, 25));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel13.setText("DATE OF JOINING");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        textField1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 150, 25));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("STUDENT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 250, -1));

        textField2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 290, 25));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\pexels-codioful-(formerly-gradienta)-7130470 (1) (1).jpg")); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(500, 150, 740, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext1ActionPerformed

    private void jtext9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String hrno = jtext1.getText();
        //System.out.println(hrno);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st1 = cot.createStatement();
            ResultSet rt = st1.executeQuery("Select *from student where hrno='" + hrno + "'");
            jtext1.setEditable(false);
            if (rt.next()) {
                //jtext1.setEditable(false);
                java.sql.Date date2 = rt.getDate("joiningdate");
                jtext12.setText(date2.toString());
                // jdate1.setDate(rt.getDate(2));
                jtext2.setText(rt.getString(3));
                jtext3.setText(rt.getString(4));
                jtext4.setText(rt.getString(5));
                java.sql.Date date1 = rt.getDate("dob");
                jtext11.setText(date1.toString());
                jtext5.setText(rt.getString(7));
                jtext6.setText(rt.getString(8));
                jtext7.setText(rt.getString(9));
                jtext8.setText(rt.getString(10));
                jtext9.setText(rt.getString(11));
                textField2.setText(rt.getString(12));
                jtext10.setText(rt.getString(13));
               textField1.setText(rt.getString(14));
            } else {
                JOptionPane.showMessageDialog(null, "STUDENT DO NOT EXIT");
                jtext1.setEditable(true);
            }
        } catch (ClassNotFoundException | SQLException e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jtext1.setText("");
                jtext2.setText("");
                jtext3.setText("");
                jtext4.setText("");
                jtext5.setText("");
                jtext6.setText("");
                jtext7.setText("");
                jtext8.setText("");
                jtext9.setText("");
                jtext10.setText("");
                jtext11.setText("");
                jtext12.setText("");
                jtext1.setEditable(true);
                textField1.setText("");
                textField2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtext1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext1KeyPressed
        // TODO add your handling code here:
                char d=evt.getKeyChar();
 if(Character.isDigit(d))
     jtext1.setVisible(true);
 else
 {
     JOptionPane.showMessageDialog(null, "pls enter digits only");
     jtext1.setText("");
    
 }
    }//GEN-LAST:event_jtext1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.TextField jtext1;
    private java.awt.TextField jtext10;
    private java.awt.TextField jtext11;
    private java.awt.TextField jtext12;
    public java.awt.TextField jtext2;
    private java.awt.TextField jtext3;
    private java.awt.TextField jtext4;
    private java.awt.TextField jtext5;
    private java.awt.TextField jtext6;
    private java.awt.TextField jtext7;
    private java.awt.TextField jtext8;
    private java.awt.TextField jtext9;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
