import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class studentfeeschoiceframe extends javax.swing.JFrame {

    public void table() {
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);
        String hrno = jtext1.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st = cot.createStatement();
            ResultSet rt = st.executeQuery("select * from fees where hrno='" + hrno + "'");
            while (rt.next()) {
                String month = rt.getString(2);
                String amount = rt.getString(3);
                Object[] ot = {month, amount};
                dt.addRow(ot);

            }
        } catch (ClassNotFoundException | SQLException e) {

        }
    }

    public studentfeeschoiceframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtext1 = new java.awt.TextField();
        jtext2 = new java.awt.TextField();
        jtext3 = new java.awt.TextField();
        jtext4 = new java.awt.TextField();
        jtext5 = new java.awt.TextField();
        jtext6 = new java.awt.TextField();
        jtext7 = new java.awt.TextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 3, 18)); // NOI18N
        jLabel1.setText("FEES OF THIS MONTH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel2.setText("HOSTEL ROLL NO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel4.setText("MOBILE NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 170, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel5.setText("BLOCK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel6.setText("ROOM NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel7.setText("MONTH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, -1));

        jLabel8.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel8.setText("AMOUNT TO BE PAY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, -1));

        jButton1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\update (1).jpg")); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\leaved (1).jpeg")); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        jtext1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 90, -1));

        jtext2.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 270, -1));

        jtext3.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 270, -1));

        jtext4.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 110, -1));

        jtext5.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 110, -1));

        jtext6.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 110, -1));

        jtext7.setFont(new java.awt.Font("Bernard MT Condensed", 3, 18)); // NOI18N
        getContentPane().add(jtext7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\cancle (2).jpeg")); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 70, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MONTH", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 500, 160));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\search (1).jpeg")); // NOI18N
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 30));

        jButton4.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        jButton4.setText("GO BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\choha\\Downloads\\pexels-codioful-(formerly-gradienta)-7130470 (1) (1).jpg")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 660));

        setBounds(500, 150, 780, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String hrno = jtext1.getText();
        SimpleDateFormat df = new SimpleDateFormat("MM-yyyy");
        Date dt = new Date();
        String month = df.format(dt);
        String amount = jtext7.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            Statement st = cot.createStatement();
            ResultSet rs = st.executeQuery("Select * from student where hrno='" + hrno + "' and status='LIVING'");
            if (rs.next()) {
                jtext1.setEditable(false);
                jtext2.setText(rs.getString(3));
                jtext3.setText(rs.getString(8));
                jtext4.setText(rs.getString(12));
                jtext5.setText(rs.getString(13));
                jtext6.setText(month);
                jtext7.setText(amount);
            } else {
                JOptionPane.showMessageDialog(null, "STUDENT DO NOT EXIST");
                jtext1.setText("");
                jtext2.setText("");
                jtext3.setText("");
                jtext4.setText("");
                jtext5.setText("");
                jtext6.setText("");
                jtext7.setText("");
                DefaultTableModel dt1 = (DefaultTableModel) jTable1.getModel();
               dt1.setRowCount(0);
            }
            table();

            ResultSet rt = st.executeQuery("select * from fees inner join student where student.status='LIVING' and fees.month='" + month + "' and fees.hrno='" + hrno + "' and student.hrno='" + hrno + "'");
            if (rt.next()) {
                jButton1.setVisible(false);
                JOptionPane.showMessageDialog(null, "FEES ALREADY PAID BY STUDENT FOR THIS MONTH");
                jtext1.setEditable(true);
                jtext1.setText("");
                jtext2.setText("");
                jtext3.setText("");
                jtext4.setText("");
                jtext5.setText("");
                jtext6.setText("");
                jtext7.setText("");
                DefaultTableModel dt1=(DefaultTableModel)jTable1.getModel();
                dt1.setRowCount(0);
            }

        } catch (ClassNotFoundException | SQLException e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String hrno = jtext1.getText();
        String month = jtext6.getText();
        String amount = jtext7.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            PreparedStatement ps = cot.prepareStatement("insert into fees values(?,?,?)");
            ps.setString(1, hrno);
            ps.setString(2, month);
            ps.setString(3, amount);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"FEES UPDATED");
            table();
//            jtext1.setText("");
            jtext2.setText("");
            jtext3.setText("");
            jtext4.setText("");
            jtext5.setText("");
            jtext6.setText("");
            jtext7.setText("");
//            DefaultTableModel dt1 = (DefaultTableModel) jTable1.getModel();
//            dt1.setRowCount(0);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jtext1.setEditable(true);
        jtext1.setText("");
        jtext2.setText("");
        jtext3.setText("");
        jtext4.setText("");
        jtext5.setText("");
        jtext6.setText("");
        jtext7.setText("");
        DefaultTableModel dt1 = (DefaultTableModel) jTable1.getModel();
        dt1.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        studentfeesframe obj1=new studentfeesframe();
        obj1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentfeeschoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentfeeschoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentfeeschoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentfeeschoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentfeeschoiceframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField jtext1;
    private java.awt.TextField jtext2;
    private java.awt.TextField jtext3;
    private java.awt.TextField jtext4;
    private java.awt.TextField jtext5;
    private java.awt.TextField jtext6;
    private java.awt.TextField jtext7;
    // End of variables declaration//GEN-END:variables
}
